main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_item
from main.views import delete_item
from main.views import get_item_json
from main.views import add_item_ajax
from main.views import increment_item_ajax
from main.views import decrement_item_ajax
from main.views import create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('increment-item-ajax/<int:id>/', increment_item_ajax, name='increment_item_ajax'),
    path('decrement-item-ajax/<int:id>/', decrement_item_ajax, name='decrement_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_product_flutter'),
]

sparkle_sphere/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from main.models import Item

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    if request.method == 'POST':
        if 'increment' in request.POST:
            item_id = request.POST.get('increment')
            item = items.get(id=item_id)
            item.amount += 1
            item.save()
            return HttpResponseRedirect(reverse('main:show_main'))
        elif 'decrement' in request.POST:
            item_id = request.POST.get('decrement')
            item = items.get(id=item_id)
            item.amount -= 1
            item.save()
            return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {
        'name': request.user.username,
        'app' : 'Sparkle Sphere',
        'class': 'PBP A',
        'items' : items,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    # Get product berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    # Hapus data
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def increment_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.amount += 1
    item.save()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def decrement_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.amount -= 1
    item.save()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'navbar.html' %}

<style>
    .edit-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #efe1cf;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        font-family: Georgia, serif;
        margin-top: 40px;
    }

    .form-group {
        text-align: left;
        margin: 10px 0;
    }

    .form-group label {
        display: block;
        text-align: left;
        margin-bottom: 5px;
        font-family: Georgia, serif;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 10px;
        margin: 10px 0;
    }

    .btn {
        background-color: #a27a55;
        color: #fff;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        display: block;
        margin: 10px auto;
        font-family: Georgia, serif;
    }

    .btn:hover {
        background-color: rgb(207, 161, 97);
        color: #fff;
    }

    h1 {
        font-family: "Lucia Bright", serif;
        text-align: center;
        margin-bottom: 30px;
    }
</style>

<div class="edit-container">
    <h1>Edit Product</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.amount.id_for_label }}">Amount:</label>
            {{ form.amount }}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <input type="submit" class="btn" value="Done Edit">
        </div>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<style>
    .login-container {
        text-align: center;
        font-family: Georgia, serif;
        margin-top: 50px;
    }

    .login-box {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #efe1cf;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        text-align: left;
        margin: 10px 0;
    }

    .form-group label {
        display: block;
        text-align: left;
        margin-bottom: 5px;
        font-family: Georgia, serif;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 10px;
        margin: 10px 0;
    }

    .login_btn {
        background-color: #a27a55;
        color: #fff;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        display: block;
        margin: 10px auto;
    }

    .login_btn:hover {
        background-color: rgb(207, 161, 97);
        color: #ffffff;
    }

    h1{
        font-family: "Lucia Bright", serif; 
    }

    p{
        font-family: Georgia, serif;
    }


</style>

<div class="login-container">
    <div class="login-box">
        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" placeholder="Username" class="form-control">
            </div>

            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" placeholder="Password" class="form-control">
            </div>

            <div class="form-group">
                <input class="btn login_btn" type="submit" value="Login">
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<style>

    .flex {
        display: flex;
        flex-wrap: nowrap;
        justify-content: flex-start;
        font-family: Georgia, serif;
    }

    .card-item {
        width: calc(25% - 10px); 
        margin: 10px;
    }

    .card {
        width: 100%;
        background-color: #ddcaaf;
    }

    .header {
        background-color: #c19e6d;
        font-family: Georgia, serif;
    }

    h1 {
        margin-top: 30px;
        font-family: Georgia, serif;
    }

    .name{
        font-size: 30px;
        margin-top: 50px;
        text-align: center;
        font-family: Georgia, serif;
    }

    .class{
        font-size: 25px;
        text-align: center;
        margin-top: 20px;
        font-family: Georgia, serif;
    }

    .total{
        font-size: 20px;
        text-align: center;
        margin-top: 20px;
        font-family: Georgia, serif;
    }

    .sesion{
        margin-top: 40px;
        margin-left: 25px;
        font-size: 15px;
        font-family: Georgia, serif;
    }

    .btn-primary {
        background-color: #c19e6d;
        border: #ffffff;
        margin-left: 25px;
        font-family: Georgia, serif;
    }

    .btn-danger {
        background-color: #dcba8a;
        border: #ffffff;
        font-family: Georgia, serif;
    }

    .logout{
        background-color: #9a7848;
        border: #ffffff;
        font-family: Georgia, serif;
    }

    .btn-primary:hover{
        background-color: #e1c194;
    }
    .footer{
        padding-top: 40px;
        margin-top: 30px;
        background-color: #6e563e;
        color: #fff;
        width: 100%; 
        position:absolute;
        font-family: Georgia, serif;
    }

    .contact{
        font-size: 30px;
        margin-bottom: 20px;
        font-family: Georgia, serif;
    }

    .delete_item, .edit_item, .increment, .decrement{
        background-color: #ae875f;
        color: #fff;
        border: #ffffff;
        font-family: Georgia, serif;
    }

    .card-title,.card-text{
        font-family: Georgia, serif;
    }

</style>

    {% include 'navbar.html' %}

    <div class="container">
        <h2 class="name">Selamat Datang {{name}} 👋🏻</h2>

        <h3 class="class">From {{class}}</h3>

        {% with total_items=items|length%}
            <h5 class="total">Kamu menyimpan {{ total_items }} jewelry pada Sparkle Sphere </h5>
        {% endwith %}

        <div class="flex" id="item-container"></div>
        
        <br />
        
        <button
            type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add Item
        </button>
        
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-primary">
                Logout
            </button>
        </a>

        <h4 class="sesion">Sesi terakhir login: {{ last_login }}</h4>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" data-bs-toggle="modal" data-bs-target="#exampleModal" id="button_add">Add Item</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer mt-5">
        <div class="container">
            <strong><p class="contact">Contact Us:</p></strong>
            <p>☎️ +62 0873-712-183</p>
            <p>🌐 www.sparklesphere.com</p>
            <p>🔮 Instagram: @SparkleSphere</p>
            <p>&copy; 2023 Sparkle Sphere. All Rights Reserved.</p>
        </div>
    </footer>

    <script>
        
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        async function refreshItems() {
            const cardContainer = document.getElementById("item-container");
            cardContainer.innerHTML = "";

            const items = await getItems();

            items.forEach((item) => {
                cardContainer.innerHTML += `
                <div class="card-item">
                    <div class="card mx-auto p-3" style="width: 18rem;">
                        <div class="card-body">
                            <h4 class="card-title">${item.fields.name}</h4>
                            <p class="card-text">Amount: ${item.fields.amount} 
                                <button class="btn increment btn-sm rounded-full" onclick="incrementAmount(${item.pk})">+</button> 
                                <button class="btn decrement btn-sm rounded-full" onclick="decrementAmount(${item.pk})">-</button>
                            </p>
                            <p class="card-text">${item.fields.description}</p>
                            <a style="justify-content: baseline;" href='edit-item/${item.pk}' class="btn edit_item" onclick="editItem(${item.pk})">Edit</a>
                            <button style="justify-content: baseline;" class="btn delete_item" onclick="deleteItem(${item.pk})">Delete</button>
                        </div>
                    </div>
                </div>`; 
            });
            document.getElementById("item-container").innerHTML = cardContainer.innerHTML;
        }

        refreshItems()

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }
        document.getElementById("button_add").onclick = addItem

        function editItem(itemId) {
            fetch(`{% url 'main:edit_item' 0 %}${itemId}/`, {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)
            document.getElementById("form").reset()
            return false
        }

        function editItem(itemId) {
        fetch(`{% url 'main:edit_item' 0 %}`.replace("0", itemId), {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
        }

        function deleteItem(itemId) {
            fetch(`{% url 'main:delete_item' 0 %}`.replace("0", itemId), {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        function incrementAmount(id) {
            fetch("/increment-item-ajax/" + id + "/", {
                method: "POST"
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        function decrementAmount(id) {
            fetch("/decrement-item-ajax/" + id + "/", {
                method: "POST"
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }
        
    </script>
{% endblock content %}

main/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar">
    <a class="navbar-brand" href="#"> Sparkle Sphere ✨ </a>
    <div class="navbar-nav ml-auto">
        <a class="nav-item nav-link" href="{% url 'main:logout' %}">Logout</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    <img src="https://i.pinimg.com/564x/c6/a7/05/c6a70583464b8be1ba6060a892df5ed0.jpg" alt="Your Logo" class="navbar-logo">
</nav>


{% block navbar_styles %}
<style>
    .custom-navbar {
        background-color:#aa8d74; 
        color: #ffffff;
    }

    .custom-heading {
        font-family: 'Font Name', sans-serif; 
        font-weight: bold; 
        color: #333;
        margin-left: 30px;
    }

    .navbar-logo {
        max-width: 80px;
        height: auto;
        margin-right: 20px;
    }

    @font-face {
    font-family: 'Playfair Display';
    src: url('/path/to/fonts/PlayfairDisplay-Regular.woff2') format('woff2'), /* Adjust the path */
         url('/path/to/fonts/PlayfairDisplay-Regular.woff') format('woff'); /* Adjust the path */
    font-weight: normal;
    font-style: normal;
    }      

    .navbar-brand {
        margin-left: 40px;
        font-size: 35px;
        font-family: 'Playfair Display', serif;
    }

    body {
    font-family: 'Roboto', sans-serif;
    }

    h1, h2, h3, h4, h5, h6, p {
        font-family: 'Roboto', sans-serif;
    }
</style>

{% endblock navbar_styles %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<style>
    .register-container {
        font-family: Georgia, serif;
        margin-top: 50px;
    }

    .register-box {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #efe1cf;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        text-align: left;
        margin: 10px 0;
    }

    .form-group label {
        text-align: left;
        display: block;
        margin-bottom: 5px;
        font-family: Georgia, serif;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 10px;
        margin: 10px 0;
    }

    .register-btn {
        background-color: #a27a55;
        color: #fff;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        display: block;
        margin: 10px auto;
        font-family: Georgia, serif;
    }

    .register-btn:hover {
        background-color: rgb(207, 161, 97);
        color: #fff;
    }

    h1 {
        font-family: "Lucia Bright", serif;
        text-align: center;
        margin-bottom: 30px;
    }

</style>

<div class="register-container">
    <div class="register-box">
        <h1>Register</h1>
        
        <form method="POST">
            {% csrf_token %}
            {{ form.username.label_tag }}
                <input type="text" name="{{ form.username.name }}" class="form-control" id="{{ form.username.id_for_label }}" required>
            {{ form.password1.label_tag }}
                <input type="password" name="{{ form.password1.name }}" class="form-control" id="{{ form.password1.id_for_label }}" required>
            {{ form.password2.label_tag }}
                <input type="password" name="{{ form.password2.name }}" class="form-control" id="{{ form.password2.id_for_label }}" required>
            <div class="form-group">
                <input class="btn register-btn" type="submit" name="submit" value="Register">
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>


{% endblock content %}